#!/bin/bash

set -e

. /opt/ca/etc/config

if [ -f "${CALOCK}" ]; then
	echo "CA Already Initialised"
	exit 1
fi

pkcs11-tool \
    --module "${PKCS11MODULE}" \
    --token "${TOKENLABEL}" \
    -l \
    -k \
    --key-type "rsa:${CAKEYSIZE}" \
    -a "${CAKEYNAME}" 
    
# --pin "${CHALLENGEPW}" \

openssl req \
    -new \
    -x509 \
    -engine pkcs11 \
    -key "${PKCS11URI}" \
    -keyform engine \
    -out "${CACERTPEM}" \
    -outform pem \
    -days 3650 \
    -set_serial "0x$(serialgen)"

openssl x509 \
    -in "${CACERTPEM}" \
    -inform pem \
    -out "${CACERTDER}" \
    -outform der

openssl x509 \
    -in "${CACERTPEM}" \
    -inform pem \
    -text \
    -noout

echo "00" > "${CASERIAL}"
echo "00" > "${CACRLSERIAL}"
touch "${CADATABASE}"

if [ ! -d "${CASIGNEDCERTS}" ]; then
	mkdir "${CASIGNEDCERTS}"
fi

echo "Writing certificate back to HSM"
pkcs11-tool \
    --module "${PKCS11MODULE}" \
    --token "${TOKENLABEL}" \
    -l \
    -w "${CACERTDER}" \
    -y cert \
    -a "${CAKEYNAME}" 

touch "${CALOCK}"
echo
echo "Sha2Wordlist for ${CACERTPEM}"
sha2wordlist ${CACERTPEM}
echo
echo "Sha2Wordlist for ${CACERTDER}"
sha2wordlist ${CACERTDER}

